// Generated by tools/generate_version.py from VERSION. Do not edit manually.
#pragma once
#define AFS_VERSION_MAJOR 3
#define AFS_VERSION_MINOR 9
#define AFS_VERSION_PATCH 0
#define AFS_VERSION_BUILD 0
#define AFS_VERSION_TEXT_A "3.9.0"
#define AFS_VERSION_TEXT_W L"3.9.0"
#define AFS_VERSION_QUAD_A "3.9.0.0"
#define AFS_VERSION_QUAD_W L"3.9.0.0"
#define AFS_PRODUCT_NAME_A "AstroFocus Studio"
#define AFS_PRODUCT_NAME_W L"AstroFocus Studio"
#define AFS_FRONTEND_TITLE_W L"AstroFocus Studio " AFS_VERSION_TEXT_W
#define AFS_ENGINE_TITLE_W L"AstroFocus Studio " AFS_VERSION_TEXT_W L" Engine"
