#!/usr/bin/env python3
"""Generate AstroFocus Studio version constants from the repository VERSION file."""
from __future__ import annotations

import argparse
import re
from pathlib import Path

VERSION_RE = re.compile(r"^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$")


def read_version(path: Path) -> tuple[int, int, int]:
    text = path.read_text(encoding="utf-8").strip()
    match = VERSION_RE.fullmatch(text)
    if not match:
        raise ValueError(f"invalid semantic version in {path}: {text!r}")
    values = tuple(int(part) for part in match.groups())
    if any(value > 65535 for value in values):
        raise ValueError("version components must fit into a 16-bit Windows version field")
    return values


def render(version: tuple[int, int, int]) -> str:
    major, minor, patch = version
    text = f"{major}.{minor}.{patch}"
    quad = f"{text}.0"
    return f'''// Generated by tools/generate_version.py from VERSION. Do not edit manually.
#pragma once
#define AFS_VERSION_MAJOR {major}
#define AFS_VERSION_MINOR {minor}
#define AFS_VERSION_PATCH {patch}
#define AFS_VERSION_BUILD 0
#define AFS_VERSION_TEXT_A "{text}"
#define AFS_VERSION_TEXT_W L"{text}"
#define AFS_VERSION_QUAD_A "{quad}"
#define AFS_VERSION_QUAD_W L"{quad}"
#define AFS_PRODUCT_NAME_A "AstroFocus Studio"
#define AFS_PRODUCT_NAME_W L"AstroFocus Studio"
#define AFS_FRONTEND_TITLE_W L"AstroFocus Studio " AFS_VERSION_TEXT_W
#define AFS_ENGINE_TITLE_W L"AstroFocus Studio " AFS_VERSION_TEXT_W L" Engine"
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version-file", type=Path, required=True)
    parser.add_argument("--header", type=Path, required=True)
    args = parser.parse_args()
    content = render(read_version(args.version_file))
    args.header.parent.mkdir(parents=True, exist_ok=True)
    if not args.header.exists() or args.header.read_text(encoding="utf-8") != content:
        args.header.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
